apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-and-services
  namespace: default
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Will
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: mydevs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-and-services