apiVersion: batch/v1
kind: Job
metadata:
  name: consumers
  labels:
    app: work-queue
    component: queue
    chapter: jobs
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: work-queue
        component: queue
        chapter: jobs
    spec:
      containers:
      - name: worker
        image: willvelida/kuard
        imagePullPolicy: Always
        command:
        - "/kuard"
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-memq-server=http://queue:8080/memq/server"
        - "--keygen-memq-queue=keygen"
      restartPolicy: OnFailure
