apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: kuard
        image: willvelida/kuard
        imagePullPolicy: Always
        command: 
          - "/kuard"
        args:
          - "--keygen-enable"
          - "--keygen-exit-on-complete"
          - "--keygen-exit-code=1"
          - "--keygen-num-to-gen=3"
      restartPolicy: OnFailure
