apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
  labels:
    name: kuard-tls
spec:
  volumes:
  - name: tls-certs
    secret:
      secretName: kuard-tls
  containers:
  - name: kuard-tls
    image: willvelida/kuard
    imagePullPolicy: Always
    volumeMounts:
    - name: tls-certs
      mountPath: "/tls"
      readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8443
