apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
  labels:
    name: kuard-config
spec:
  volumes:
    - name: config-volume
      configMap:
        name: my-config
  restartPolicy: Never
  containers:
  - name: kuard-config
    image: willvelida/kuard
    imagePullPolicy: Always
    command:
    - "/kuard"
    - "${EXTRA_PARAM}"
    env:
      # An example of an environment variable used inside the container
      - name: ANOTHER_PARAM
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: another-parameter
      # An example of an environment variable passed to the command to start
      - name: EXTRA_PARAM
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: extra-parameter
    volumeMounts:
      # Mounting the ConfigMap as a set of files
      - name: config-volume
        mountPath: /config
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
